print('------Simple biodata creation------')
Name = input('Enter name: ')
Age = input('How old are you?: ')
Hobby = input('Whats your main hobby?: ')
Country = input('Where are you from?: ')
print('----- Your Mini Biodata-----')
print('Name: ', Name)
print('Age: ', Age)
print('Hobby: ', Hobby)
print('Origin: ', Country)
print('----------------------')